server:
  port: 9900

  
spring:
  h2:
    console: 
      enabled: true
      path: /h2
  datasource: 
    url: jdbc:h2:mem:planetdb
    username: sun
    password: 
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  
  
  application:
    name: My-Very-Fun-Planet-Service  
  #config:
  # import: 'optional:consul:'